from __future__ import annotations

from abc import ABC, abstractmethod
from copy import deepcopy
from typing import Any, Dict

from .errors import ValidationError


class Planner(ABC):
    """
    Planner produces a Plan from an Intent.

    Framework constraint:
    - Planning must be deterministic (given inputs and declared environment constraints).
    - Nucleus must not execute arbitrary commands generated by AI.
    """

    @abstractmethod
    def plan(self, intent: Dict[str, Any]) -> Dict[str, Any]:
        raise NotImplementedError


class StaticPlanner(Planner):
    """
    Deterministic planner used for framework bring-up and testing.
    Returns a predefined plan template and injects the provided intent.
    """

    def __init__(self, plan_template: Dict[str, Any]):
        self._template = deepcopy(plan_template)

    def plan(self, intent: Dict[str, Any]) -> Dict[str, Any]:
        if not isinstance(intent, dict):
            raise ValidationError(code="intent.invalid", message="Intent must be an object")

        plan = deepcopy(self._template)
        plan["intent"] = intent

        # Ensure required top-level ID exists.
        if "plan_id" not in plan or not isinstance(plan["plan_id"], str) or not plan["plan_id"]:
            raise ValidationError(code="plan.invalid", message="plan_id must be a non-empty string")

        return plan

